name: main

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: 0.5.16
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('uv.lock') }}

      - run: echo "UV_PYTHON=${{ steps.setup-python.outputs.python-path }}" >> "$GITHUB_ENV"
      - run: uv sync --all-extras --locked
      - run: uv run ruff format --check
      - run: uv run ruff check
      - run: uv run pyright --warnings
      - run: uv run playwright install chromium
      - run: uv run pytest
      - run: uv run sphinx-build --fail-on-warning docs docs/dist
      - run: uv build
      - run: echo "${GITHUB_EVENT_NAME}"
      - run: cat "${GITHUB_EVENT_PATH}"
      - if: matrix.python == '3.13' && github.event_name == 'workflow_call'
        run: uv run ./dev/check_release_version.py
      - if: matrix.python == '3.13' && github.event_name == 'workflow_call'
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
